"""Fixtures for the assistant suite.

Every PDF used here is generated by the test that needs it. No sourcebook text,
page image, or extracted excerpt is ever committed, and no test touches a real
Redline installation: the application-data directory is redirected into a
temporary folder for the whole session.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from assistant import credentials, paths  # noqa: E402

ARMOR_RULE = (
    "Armor ablates by one point whenever it stops damage from an attack. Ablation "
    "reduces stopping power until the armor is repaired at a shop."
)
CRITICAL_RULE = (
    "A natural ten on the die explodes: roll the die again and add the new result "
    "to the total before comparing it to the difficulty value."
)
DLC_RULE = (
    "A ballistic shield in this supplement ablates two points of stopping power "
    "when it stops a shotgun shell rather than one."
)


@pytest.fixture(autouse=True)
def private_home(tmp_path, monkeypatch):
    """Redirect the private library into a throwaway directory."""

    home = tmp_path / "appdata"
    monkeypatch.setenv(paths.HOME_ENV, str(home))
    paths.ensure_layout()
    return home


@pytest.fixture
def make_pdf(tmp_path):
    """Build a small text PDF from a list of page strings."""

    import pymupdf

    def build(name: str, pages: list[str], encrypt: str = "") -> Path:
        document = pymupdf.open()
        for body in pages:
            page = document.new_page()
            # A text box wraps, so a page holds all of its text rather than
            # clipping it at the page edge the way insert_text would.
            page.insert_textbox(page.rect + (56, 56, -56, -56), body, fontsize=11)
        destination = tmp_path / name
        if encrypt:
            document.save(
                destination,
                encryption=pymupdf.PDF_ENCRYPT_AES_256,
                owner_pw=encrypt,
                user_pw=encrypt,
            )
        else:
            document.save(destination)
        document.close()
        return destination

    return build


@pytest.fixture
def image_pdf(tmp_path):
    """A PDF holding a page image and no text, standing in for a scan."""

    import pymupdf

    document = pymupdf.open()
    pixmap = pymupdf.Pixmap(pymupdf.csRGB, pymupdf.IRect(0, 0, 240, 320))
    pixmap.set_rect(pixmap.irect, (220, 220, 220))
    for _ in range(3):
        page = document.new_page()
        page.insert_image(pymupdf.Rect(0, 0, 240, 320), pixmap=pixmap)
    destination = tmp_path / "scanned.pdf"
    document.save(destination)
    document.close()
    return destination


@pytest.fixture
def vault(monkeypatch):
    """An in-memory stand-in for the operating-system credential vault."""

    class FakeVault:
        def __init__(self) -> None:
            self.entries: dict[tuple[str, str], str] = {}

        def set_password(self, service: str, account: str, password: str) -> None:
            self.entries[(service, account)] = password

        def get_password(self, service: str, account: str) -> str | None:
            return self.entries.get((service, account))

        def delete_password(self, service: str, account: str) -> None:
            del self.entries[(service, account)]

    fake = FakeVault()
    monkeypatch.setattr(credentials, "_backend", lambda: fake)
    return fake
